<template><div><div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code class="language-bash"><span class="line"><span class="token function">podman</span> run <span class="token parameter variable">--replace</span> <span class="token parameter variable">-dt</span> <span class="token parameter variable">--name</span> caddy --cap-add<span class="token operator">=</span>NET_ADMIN <span class="token parameter variable">-p</span> <span class="token number">80</span>:80 <span class="token parameter variable">-p</span> <span class="token number">443</span>:443 <span class="token parameter variable">-p</span> <span class="token number">443</span>:443/udp <span class="token punctuation">\</span></span>
<span class="line">    <span class="token parameter variable">-v</span> <span class="token variable"><span class="token variable">$(</span><span class="token builtin class-name">pwd</span><span class="token variable">)</span></span>/www:/srv <span class="token punctuation">\</span></span>
<span class="line">    <span class="token parameter variable">-v</span> <span class="token variable"><span class="token variable">$(</span><span class="token builtin class-name">pwd</span><span class="token variable">)</span></span>/caddy_data:/data <span class="token punctuation">\</span></span>
<span class="line">    <span class="token parameter variable">-v</span> <span class="token variable"><span class="token variable">$(</span><span class="token builtin class-name">pwd</span><span class="token variable">)</span></span>/caddy_config:/config <span class="token punctuation">\</span></span>
<span class="line">    <span class="token parameter variable">-v</span> <span class="token variable"><span class="token variable">$(</span><span class="token builtin class-name">pwd</span><span class="token variable">)</span></span>/Caddyfile:/etc/caddy/Caddyfile <span class="token punctuation">\</span></span>
<span class="line">    caddy</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


