<template><div><div class="language-swift line-numbers-mode" data-highlighter="prismjs" data-ext="swift"><pre v-pre><code class="language-swift"><span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token keyword">extension</span> <span class="token class-name">Binding</span> <span class="token keyword">where</span> <span class="token class-name">Value</span> <span class="token operator">==</span> <span class="token class-name">Int</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">public</span> <span class="token keyword">func</span> <span class="token function-definition function">float</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">-></span> <span class="token class-name">Binding</span><span class="token operator">&lt;</span><span class="token class-name">Float</span><span class="token operator">></span> <span class="token punctuation">{</span></span>
<span class="line">        <span class="token keyword">return</span> <span class="token class-name">Binding</span><span class="token operator">&lt;</span><span class="token class-name">Float</span><span class="token operator">></span><span class="token punctuation">(</span><span class="token keyword">get</span><span class="token punctuation">:</span><span class="token punctuation">{</span> <span class="token class-name">Float</span><span class="token punctuation">(</span><span class="token keyword">self</span><span class="token punctuation">.</span>wrappedValue<span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">            <span class="token keyword">set</span><span class="token punctuation">:</span> <span class="token punctuation">{</span> <span class="token keyword">self</span><span class="token punctuation">.</span>wrappedValue <span class="token operator">=</span> <span class="token class-name">Int</span><span class="token punctuation">(</span><span class="token short-argument">$0</span><span class="token punctuation">)</span><span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span>
<span class="line"><span class="token operator">...</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// self.$data.count is Binding&lt;Int></span></span>
<span class="line"><span class="token class-name">Slider</span><span class="token punctuation">(</span>value<span class="token punctuation">:</span> <span class="token keyword">self</span><span class="token punctuation">.</span>$data<span class="token punctuation">.</span>count<span class="token punctuation">.</span><span class="token function">float</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">in</span><span class="token punctuation">:</span><span class="token number">1</span><span class="token operator">...</span><span class="token number">16</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">                <span class="token class-name">Text</span><span class="token punctuation">(</span><span class="token string-literal"><span class="token string">"Number"</span></span><span class="token punctuation">)</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


